config/routes.rb
Rails.application.routes.draw do



  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:show]

  resources :chalets, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :account do
    resource :user, only: [:show]
    resources :chalets, only: [:new, :create, :destroy, :index]
    resources :chalets, only: [:edit, :update] do
      resources :chalet_pictures, only: [:destroy]
    end
    resources :bookings, only: :index
  end




end

app/models/chalet.rb
class Chalet < ActiveRecord::Base
  belongs_to :user
  has_many :bookings
  has_many :chalet_pictures, dependent: :destroy

  accepts_nested_attributes_for :chalet_pictures, reject_if: lambda { |c| c['picture'].nil? }

  validates :title, presence: true, uniqueness: true
  validates :city, presence: true
  validates :daily_price, presence: true, numericality: true
  validates :max_nb_of_guests, presence: true, numericality: true

  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  def available?(arrival_date, departure_date)
    results = self.bookings.select { |booking|
      (departure_date < booking.arrive_on) || (arrival_date > booking.leave_on)
    }
    results.count == self.bookings.count
  end
end

app/controllers/account/chalets_controller.rb
module Account
  class ChaletsController < BaseController
    before_action :set_chalet, only: [:edit, :update, :destroy]
    def new
      @chalet = current_user.chalets.new
      3.times {@chalet.chalet_pictures.build}
    end

    def create
      chalet_params[:city] = chalet_params[:city].capitalize
      @chalet = current_user.chalets.new(chalet_params)
      @chalet.availability = true


      if @chalet.save!

      flash[:notice] = "Your chalet has been added."
        redirect_to account_user_path
      else
        flash[:alert] = "Something went wrong."
        render 'new'
      end
    end

    def edit
      3.times { @chalet.chalet_pictures.build }
    end

    def update
      if @chalet.update(chalet_params)

        flash[:notice] = "Your chalet has been updated."
        redirect_to chalet_path(@chalet)
      else
        flash[:alert] = "Something went wrong."
        render 'edit'
      end
    end

    def destroy
      @chalet.destroy
      redirect_to account_user_path
    end

    def index
      @chalets = current_user.chalets.all
    end


    private
    def chalet_params
      params.require(:chalet).permit(:title, :description, :city, :daily_price, :max_nb_of_guests, :availability, chalet_pictures_attributes: [ :picture ])
    end

    def set_chalet
      @chalet = Chalet.find(params[:id])
    end

  end
end

app/controllers/chalets_controller.rb
class ChaletsController < ApplicationController
  def index
  end

  def show
    @chalet = Chalet.find(params[:id])
    @user = User.find(@chalet.user_id)
  end

  def search
    @city = params[:search][:query].capitalize
    @chalets = Chalet.near(@city, 500)
    @markers = Gmaps4rails.build_markers(@chalets) do |chalet, marker|
      marker.lat chalet.latitude
      marker.lng chalet.longitude
    end
  end

end

app/helpers/chalets_helper.rb
module ChaletsHelper
end

app/views/chalets/_chalet.html.erb
<div class="col-xs-12 col-md-6">
  <div class="card">
    <div class="card-head">
      <% if chalet.chalet_pictures.any? %>
        <%= image_tag(chalet.chalet_pictures.first.picture.url(:medium), alt: "Chalet Picture") %>
      <% else %>
        <%= image_tag("http://lorempixel.com/g/400/300/nature/") %>
      <% end %>
      <div class="card-title">
        <h2><%= chalet.title %></h2>
        <h3><%= chalet.city %></h3>
      </div>
    </div>
    <div class="card-content">
      <p><%= "#{chalet.daily_price} euros a night" %></p>
      <p><%= "#{chalet.max_nb_of_guests} guests per night" %></p>
    </div>
    <div class="card-action">
      <%= link_to "View", chalet_path(chalet), class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/chalets/search.html.erb
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

<div id="map" style="width: 100%; height: 400px;"></div>
<h1 class="text-center padded">Chalets near <%= @city %></h1>

<div class="body-wrapper">
  <div class="row">
    <% @chalets.each do |chalet| %>
      <%= render "chalets/chalet", chalet: chalet %>
    <% end %>
  </div>
</div>

app/views/chalets/show.html.erb
<div class="body-wrapper">

<div class="chalet-name text-right">
  <h2><%= @chalet.title %> </h1>
  <h3> <%= @chalet.city %> </h2>
</div>


  <% if @chalet.chalet_pictures.any? %>
    <div class="centered-carousel">
      <div class="owl-carousel">
        <% @chalet.chalet_pictures.each do |pic| %>
          <div> <%= image_tag pic.picture.url(:cover) %> </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="centered-carousel">
      <div class="owl-carousel">
          <div> <%= image_tag "default_chalet_picture.jpg" %> </div>
      </div>
    </div>
  <% end %>


  <% if current_user == @chalet.user %>
    <div class="booking">
      <%= link_to "Edit chalet", edit_account_chalet_path(@chalet), class: "btn btn-success btn-lg" %>
      <%= link_to "Remove chalet", account_chalet_path(@chalet), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-success btn-lg" %>
    </div>

  <% elsif user_signed_in? %>
    <div class="booking">
      <%= link_to "Book this chalet", new_chalet_booking_path(@chalet), class: "btn btn-success btn-lg" %>
    </div>

  <% else %>
    <div class="booking">

      <%= link_to "Sign in to book this chalet", new_user_session_path, class: "btn btn-success btn-lg" %>
    </div>
  <% end %>





<div class="container" id="chalet-show">
  <div class="row">
    <div class="col-xs-12 col-md-4" id="owner">
      <%= image_tag @user.picture(:thumb), class: "picture-owner" %>
      <p> <%= link_to @user.first_name, user_path(@user) %> </p>
      <p> <%= @user.email %> </p>
    </div>


    <div class="col-xs-12 col-md-4" id="guests">
      <h3> <i class="fa fa-bed"></i>: <%= @chalet.max_nb_of_guests %> </h3>
    </div>

    <div class="col-xs-12 col-md-4" id="price">
      <h3> <i class="fa fa-money"></i>: <%= @chalet.daily_price %>$/night</h3>
    </div>

    <div class="col-xs-12 col-md-6" id="description">
      <p> <%= @chalet.description %> </p>
    </div>
  </div>
</div>

</div>

app/views/chalets/show.html.slim
h1 Chalet

.card
  .card-head
    = image_tag("home-background.jpg", size: "300x300", alt: "Chalet Picture")
    .card-title
      h2 = @chalet.title
      h3 = @chalet.city
  .card-content
    p = @chalet.description
    p = "#{@chalet.daily_price} euros a night"
    p = "#{@chalet.max_nb_of_guests} guests per night"
  .card-action
    = link_to "Back", chalets_path, class: "btn btn-default"
    = link_to "Book chalet", new_chalet_booking_path(@chalet), class: "btn btn-primary"