config/routes.rb
Rails.application.routes.draw do



  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:show]

  resources :chalets, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :account do
    resource :user, only: [:show]
    resources :chalets, only: [:new, :create, :destroy, :index]
    resources :chalets, only: [:edit, :update] do
      resources :chalet_pictures, only: [:destroy]
    end
    resources :bookings, only: :index
  end




end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :chalet

  validates :user, presence: true
  validates :chalet, presence: true
  validates :arrive_on, presence: true
  validates :leave_on, presence: true
  validates :total_price, presence: true, numericality: true
  validate :arrive_in_future?
  validate :leave_after_arrive?

  def arrive_in_future?
    if arrive_on < Date.current
      errors.add(:arrive_on, 'Arrival date must be in the future')
    end
  end

  def leave_after_arrive?
    if leave_on < arrive_on
      errors.add(:leave_on, 'Leaving date must be after arrival date')
    end
  end

end

app/controllers/account/bookings_controller.rb
module Account
  class BookingsController < BaseController

    def index
      @userbookings = current_user.bookings
      @relevant_bookings = @userbookings.select do |booking|
        booking.arrive_on > Time.now
      end
    end

  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :user_signed_in?

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @chalet = Chalet.find(params[:chalet_id])

    @booking.chalet_id = @chalet.id
    @booking.total_price = (@booking.leave_on - @booking.arrive_on) * @chalet.daily_price
    if !@chalet.available?(arrival_date, departure_date)
      flash.alert = "Hey loser, the chalet is not available on your selected dates, so fuck off."
      render 'new'
    elsif @chalet.user_id == current_user.id
      redirect_to account_user_path
      flash.alert = "Hey loser, you're trying to book your own place, so fuck off."

    elsif @booking.save!
      redirect_to account_user_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def booking_params
      params.require(:booking).permit(:arrive_on, :leave_on, :chalet_id, :user_id)
  end

  def arrival_date
    Date.parse(booking_params[:arrive_on])
  end

  def departure_date
    Date.parse(booking_params[:leave_on])
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_new_booking.html.erb
<div class="container">
  <div class="row centered">
    <div class="col-xs-12 col-ml-4">

      <%= simple_form_for([ @booking ], url: chalet_bookings_path, method: :post) do |f| %>
        <%= f.input :arrive_on, as: :string, input_html: { class: "datepicker" }, label: "Your arrival date" %>
        <%= f.input :leave_on, as: :string, input_html: { class: "datepicker" }, label: "Your departure date" %>
        <%= f.button :submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 padded">
      <h1 class= "text-center">Create a new booking</h1>
      <%= render 'new_booking' %>
    </div>
  </div>
</div>