config/routes.rb
Rails.application.routes.draw do



  root to: "home#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:show]

  resources :chalets, only: [:index, :show] do
    collection do
      get 'search'
    end
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :account do
    resource :user, only: [:show]
    resources :chalets, only: [:new, :create, :destroy, :index]
    resources :chalets, only: [:edit, :update] do
      resources :chalet_pictures, only: [:destroy]
    end
    resources :bookings, only: :index
  end




end

app/views/layouts/_footer.html.slim
div#footer
  .container-fluid
    .row
      .col-xs-12.col-sm-6
        ul class="list-inline pull-left"
          li
            a href="http://www.facebook.com"
              i class="fa fa-facebook-official"
          li
            a href="http://www.twitter.com"
              i class="fa fa-twitter"
          li
            a href="http://www.instagram.com"
              i class="fa fa-instagram"

      .col-xs-12.col-sm-6
        p class="pull-right" This site is brought to you by WMN Inc.

app/views/layouts/_navbar.html.slim
nav class="navbar-snowbnb" role="navigation"
  .container-fluid
    .row
      div.navbar-section.col-xs-12.col-md-6.col-lg-4
        = link_to "/"
          = inline_svg "SnowBnB_logo.svg", class: 'logo'

      div.navbar-section.col-xs-12.col-md-6.col-lg-4
        - unless current_page?(root_path)
          = form_for :search, url: search_chalets_path, method: :get do |f|
            = f.text_field :query, autofocus: true, class: "form-control", placeholder: 'Where do you want to go?'

      div.navbar-section.col-xs-12.col-md-6.col-lg-4

        - if user_signed_in?
          div class="dropdown"
            = link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do
              = image_tag current_user.picture(:thumb), class: "img-avatar"
              = current_user.first_name

            ul class="dropdown-menu dropdown-menu-right" role="menu"
              li
                = link_to account_chalets_path do
                  i class="fa fa-home"
                  |  My Chalets

              li
                = link_to account_bookings_path do
                  i class="fa fa-book"
                  |  My Bookings

              li
                = link_to account_user_path do
                  i class="fa fa-user"
                  |  My Profile

              li
                = link_to destroy_user_session_path, method: :delete do
                  i class="fa fa-sign-out"
                  |  Sign out
        - else
          ul.list-inline
            li
              = link_to "Sign in", new_user_session_path, class: 'btn btn-default'
            li
              = link_to user_omniauth_authorize_path(:facebook), class: 'btn btn-primary btn-fb' do
                i class="fa fa-facebook-square"
                |  Sign in
            li
              = link_to "Sign up", new_user_registration_path, class: 'btn btn-primary'

app/views/layouts/application.html.slim
html
  head
    title SnowBnB
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"

body
  = render 'layouts/navbar'

  - if flash[:notice]
    div class="alert alert-info fade in"
      button class="close" data-dismiss="alert"×
      = flash[:notice]

  - if flash[:alert]
    div class="alert alert-error fade in"
      button class="close" data-dismiss="alert"×
      = flash[:alert]

  = yield

  = render 'layouts/footer'



  = javascript_include_tag 'application'
  = javascript_include_tag 'https://maps.google.com/maps/api/js?sensor=false'
  = javascript_include_tag 'https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'
  = yield(:after_js)